!include common.yaml
---
- package: iniconfig
  name: iniconfig
  version: "{{versions.iniconfig}}"
  vendor_source: https://files.pythonhosted.org/packages/23/a2/97899f6bd0e873fed3a7e67ae8d3a08b21799430fb4da15cfedf10d6e2c2/{{name}}-{{version}}.{{extension}}
  description: |
    Iniconfig {{version}} brain-dead simple config-ini parsing
