# Copyright (c) 2000 - 2019 The Regents of the University of California.
# All rights reserved.	
#
# This makefile includes the generic yaml2rpm Makefile 
# building packages for python 3
#

.PHONY:  modules.build 

include $(YAML2RPM_HOME)/sys/Makefile

BOOTSTRAP_MODULES_FILE=modules.bootstrap.python
MODULES_FILE = modules.build.python
PYVERSIONS = pyversions3.yaml
EXTRAMODS=versions.yaml
MANIFEST_FILE = modules.manifest

GENEXTRAS +=  --map="{'pyversions.yaml':'$(PYVERSIONS)'}" 

# Modules are common plus python3-specific
MODULES = $(shell sed '1d' versions.yaml  | awk -F: '{print $$1}' | sed 's/$$/.yaml/') \
          $(shell sed '1d' $(EXTRAMODS) | awk -F: '{print $$1}' | sed 's/$$/.yaml/')

PKGS = $(MODULES:.yaml=.pkg)

default: diag2 modules.build 
	make -f $(THISMAKE) $(PKGS) 

modules.build: 
	/bin/rm -f $(MODULES_FILE)
	/bin/rm -f $(MANIFEST_FILE)
	echo $(MODULES) | sed -e 's/ //g' -e 's/\.yaml/\n/g' > $(MODULES_FILE)
	/bin/cp $(MODULES_FILE) $(MANIFEST_FILE)
	echo  python >> $(MANIFEST_FILE)
	echo python-module >> $(MANIFEST_FILE)

clean:
	- /bin/rm $(MODULES_FILE)
	- /bin/rm $(MANIFEST_FILE)

diag2: diag
	echo "Modules: $(MODULES)"
	echo "PKGS: $(PKGS)"
	echo $(GENERATE)
	echo $(MODULES_FILE)
	cat $(BOOTSTRAP_MODULES_FILE)
